
[build]
  base = "apps/website"
  command = "curl -fsSL https://d2lang.com/install.sh | sh -s -- && export PATH=$HOME/.local/bin:$PATH && pnpm -w run site:build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
